---

- name: Set PostgreSQL environment variables.
  template:
    src: postgres.sh.j2
    dest: /etc/profile.d/postgres.sh
    mode: 0644
  become: true
  notify: Restart PostgreSQL

- name: Ensure PostgreSQL data directory exists.
  file:
    path: "{{ postgresql_data_directory }}"
    owner: postgres
    group: postgres
    state: directory
    mode: 0700
  become: true

- name: Ensure PostgreSQL unix socket dirs exist.
  file:
    path: "{{ item }}"
    state: directory
    owner: postgres
    group: postgres
    mode: 02775
  become: true
  with_items:
    - /var/run/postgresql

- name: Check if PostgreSQL database is initialized.
  stat:
    path: "{{ postgresql_data_directory }}/PG_VERSION"
  become: true
  register: _pgdata_dir_version

- name: Ensure PostgreSQL database is initialized.
  command: "{{ postgresql_binary_directory }}/initdb -D '{{ postgresql_data_directory }}' --locale={{ postgresql_locale }} --encoding=UTF8 --text-search-config=pg_catalog.english"
  when: not _pgdata_dir_version.stat.exists
  become: yes
  become_user: postgres
  # See: https://github.com/ansible/ansible/issues/16048#issuecomment-229012509
  vars:
    ansible_ssh_pipelining: true
